# -*- coding: utf-8 -*-
"""AIST_CODE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gryIQ_GaaBi3Lazw4rqpwKfHr7kHVdew
"""

from datasets import load_dataset

ds = load_dataset("dianavdavidson/MUCS-Hinglish")

print(ds)
print(ds["test"].column_names)
print(ds["test"].features)


# ============================================================
# PART 0 — INSTALL
# ============================================================
# !pip install -q datasets soundfile librosa numpy scipy tqdm huggingface_hub pandas

import os
import random
import shutil
import numpy as np
import librosa
import soundfile as sf
import pandas as pd
from tqdm import tqdm
from datasets import load_dataset

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

TARGET_SR = 16000
N_CLIPS = 20          # quick benchmark first; raise to 100-150 once you know timing
SPLIT_TO_USE = "test"  # "test" (3.14k) is a sensible held-out eval pool; use "train" if you prefer
SNR_LEVELS = [15, 10, 5]
NOISE_TYPES = ["traffic", "babble", "indoor"]

ROOT = "/content/hinglish_robustness"
NOISE_SRC_DIR = "/content/noise_src"   # raw downloaded noise, sorted by type

# ============================================================
# PART 1 — LOAD DATASET AND INSPECT IT
# ============================================================
print("Loading MUCS-Hinglish dataset...")
ds = load_dataset("dianavdavidson/MUCS-Hinglish")
print(ds)  # shows splits: train (52.8k), test (3.14k)

example = ds[SPLIT_TO_USE][0]
print("\nExample record keys:", list(example.keys()))
for k, v in example.items():
    preview = str(v)
    if len(preview) > 200:
        preview = preview[:200] + "..."
    print(f"  {k}: {preview}")

# Confirmed from actual dataset inspection:
#   features: audio, segment_id, transcript, speaker_id, segment_part,
#             ratio_english_words, ratio_hindi_words, english_words,
#             count_english_words, count_dev_words, ratio_english_words_range
#   audio is already 16kHz (Audio(sampling_rate=16000)) -> no resampling needed
AUDIO_COL = "audio"
TEXT_COL = "transcript"

assert AUDIO_COL in example, f"'{AUDIO_COL}' not found — check keys above and fix AUDIO_COL"
assert TEXT_COL in example, f"'{TEXT_COL}' not found — check keys above and fix TEXT_COL"

# Code-switching filter: only keep clips that actually contain BOTH Hindi
# and English words, so we're not accidentally benchmarking on monolingual
# segments. ratio_english_words_range looks like a pre-binned category
# (e.g. "0-25", "25-50", ...) — we print unique values once so you can see
# the actual bins and adjust MIN_HINDI_RATIO / MIN_ENGLISH_RATIO below.
print("\nUnique ratio_english_words_range values (sample):")
print(set(ds[SPLIT_TO_USE][:500]["ratio_english_words_range"]))

MIN_HINDI_RATIO = 0.1     # require at least 10% Hindi words
MIN_ENGLISH_RATIO = 0.1   # require at least 10% English words

# ============================================================
# PART 2 — DOWNLOAD NOISE (MUSAN subset via Hugging Face mirror)
# ============================================================
# There isn't a single HF dataset that's pre-labeled exactly "traffic /
# babble / indoor", so we pull from two well-known sources and sort them
# into our three folders:
#   - MUSAN "noise" split  -> traffic / indoor (general ambient/background)
#   - MUSAN "speech" split -> babble (overlapping speech = babble noise)
#
# Adjust MUSAN_DATASET_ID if this mirror is unavailable when you run this;
# search "musan" on huggingface.co/datasets for an alternative mirror.
MUSAN_DATASET_ID = "DTU54DL/musan"   # example community mirror; verify availability

os.makedirs(NOISE_SRC_DIR, exist_ok=True)
for nt in NOISE_TYPES:
    os.makedirs(os.path.join(NOISE_SRC_DIR, nt), exist_ok=True)

def save_musan_subset(hf_split_name, target_noise_type, n_files=15):
    print(f"\nDownloading MUSAN '{hf_split_name}' -> {target_noise_type} ({n_files} files)")
    musan = load_dataset(MUSAN_DATASET_ID, split=hf_split_name, streaming=True)
    out_dir = os.path.join(NOISE_SRC_DIR, target_noise_type)
    count = 0
    for row in musan:
        if count >= n_files:
            break
        audio = row["audio"]
        arr = np.array(audio["array"], dtype=np.float32)
        sr = audio["sampling_rate"]
        if sr != TARGET_SR:
            arr = librosa.resample(arr, orig_sr=sr, target_sr=TARGET_SR)
        out_path = os.path.join(out_dir, f"{target_noise_type}_{count:03d}.wav")
        sf.write(out_path, arr, TARGET_SR)
        count += 1
    print(f"  saved {count} files to {out_dir}")

# NOTE: MUSAN's "noise" split mixes many ambient types (traffic-like, indoor
# hums, etc.) rather than being pre-labeled by scene. For a first pass we
# split it 50/50 into traffic/ and indoor/; babble comes from "speech".
# This is a reasonable approximation for a benchmark, but note it in your
# methodology as an approximation, not hand-verified scene labels.
try:
    save_musan_subset("speech", "babble", n_files=15)
    save_musan_subset("noise", "traffic", n_files=15)
    save_musan_subset("noise", "indoor", n_files=15)
except Exception as e:
    print(f"\n[!] Automatic MUSAN download failed: {e}")
    print("    Fallback: manually upload .wav noise files into:")
    for nt in NOISE_TYPES:
        print(f"      {os.path.join(NOISE_SRC_DIR, nt)}/")
    print("    Any real traffic/babble/cafe recordings work — even a few")
    print("    minutes-long clip per category is enough (we crop random")
    print("    segments from it for each mix).")

# ============================================================
# PART 3 — BUILD FOLDER STRUCTURE
# ============================================================
def make_dirs():
    os.makedirs(os.path.join(ROOT, "clean"), exist_ok=True)
    for nt in NOISE_TYPES:
        for snr in SNR_LEVELS:
            os.makedirs(os.path.join(ROOT, nt, f"{snr}db"), exist_ok=True)

make_dirs()
print(f"\nFolder structure created under {ROOT}")

# ============================================================
# PART 4 — SUBSAMPLE CLIPS (filtered for genuine code-switching)
# ============================================================
data = ds[SPLIT_TO_USE]

print("\nFiltering for genuinely code-switched clips "
      f"(Hindi ratio >= {MIN_HINDI_RATIO}, English ratio >= {MIN_ENGLISH_RATIO})...")
cs_data = data.filter(
    lambda ex: ex["ratio_hindi_words"] >= MIN_HINDI_RATIO
    and ex["ratio_english_words"] >= MIN_ENGLISH_RATIO
)
print(f"Code-switched clips available: {len(cs_data)} / {len(data)}")

if len(cs_data) < N_CLIPS:
    print(f"[!] Only {len(cs_data)} clips pass the filter, fewer than N_CLIPS={N_CLIPS}. "
          "Lower MIN_HINDI_RATIO / MIN_ENGLISH_RATIO or increase N_CLIPS accordingly.")

indices = list(range(len(cs_data)))
random.shuffle(indices)
indices = indices[:N_CLIPS]
subset = cs_data.select(indices)
print(f"\nUsing {len(subset)} clips from split '{SPLIT_TO_USE}' (seed={SEED})")

# ============================================================
# PART 5 — NOISE MIXING UTILITIES
# ============================================================
def load_noise_files(noise_type):
    folder = os.path.join(NOISE_SRC_DIR, noise_type)
    files = [os.path.join(folder, f) for f in os.listdir(folder) if f.endswith(".wav")]
    if not files:
        raise FileNotFoundError(
            f"No noise wavs found in {folder}. See Part 2 fallback instructions above."
        )
    return files

noise_file_cache = {nt: load_noise_files(nt) for nt in NOISE_TYPES}

def get_random_noise_clip(noise_type, target_len):
    files = noise_file_cache[noise_type]
    path = random.choice(files)
    noise, sr = librosa.load(path, sr=TARGET_SR, mono=True)
    if len(noise) < target_len:
        reps = int(np.ceil(target_len / len(noise)))
        noise = np.tile(noise, reps)
    start = random.randint(0, len(noise) - target_len) if len(noise) > target_len else 0
    return noise[start:start + target_len]

def mix_at_snr(clean, noise, snr_db):
    clean_power = np.mean(clean ** 2) + 1e-10
    noise_power = np.mean(noise ** 2) + 1e-10
    target_noise_power = clean_power / (10 ** (snr_db / 10))
    scale = np.sqrt(target_noise_power / noise_power)
    noisy = clean + noise * scale
    peak = np.max(np.abs(noisy))
    if peak > 1.0:
        noisy = noisy / peak
    return noisy.astype(np.float32)

def get_audio_array(sample):
    audio = sample[AUDIO_COL]
    arr = np.array(audio["array"], dtype=np.float32)
    sr = audio["sampling_rate"]
    if sr != TARGET_SR:
        arr = librosa.resample(arr, orig_sr=sr, target_sr=TARGET_SR)
    return arr

# ============================================================
# PART 6 — GENERATE CLEAN + NOISY FILES, BUILD metadata.csv
# ============================================================
metadata_rows = []

print("\nWriting clean files...")
for i, sample in enumerate(tqdm(subset)):
    clean_audio = get_audio_array(sample)
    reference = sample[TEXT_COL]
    clip_id = f"clip_{i:04d}"

    clean_path = os.path.join(ROOT, "clean", f"{clip_id}.wav")
    sf.write(clean_path, clean_audio, TARGET_SR)

    base_meta = {
        "clip_id": clip_id,
        "segment_id": sample.get("segment_id"),
        "speaker_id": sample.get("speaker_id"),
        "ratio_english_words": sample.get("ratio_english_words"),
        "ratio_hindi_words": sample.get("ratio_hindi_words"),
    }

    metadata_rows.append({
        **base_meta,
        "condition": "clean",
        "noise_type": "none",
        "snr_db": "clean",
        "filepath": clean_path,
        "reference_text": reference,
        "duration_sec": len(clean_audio) / TARGET_SR,
    })

    for noise_type in NOISE_TYPES:
        for snr in SNR_LEVELS:
            noise_clip = get_random_noise_clip(noise_type, len(clean_audio))
            noisy_audio = mix_at_snr(clean_audio, noise_clip, snr)
            noisy_path = os.path.join(ROOT, noise_type, f"{snr}db", f"{clip_id}.wav")
            sf.write(noisy_path, noisy_audio, TARGET_SR)

            metadata_rows.append({
                **base_meta,
                "condition": noise_type,
                "noise_type": noise_type,
                "snr_db": snr,
                "filepath": noisy_path,
                "reference_text": reference,
                "duration_sec": len(clean_audio) / TARGET_SR,
            })

metadata_df = pd.DataFrame(metadata_rows)
metadata_csv_path = os.path.join(ROOT, "metadata.csv")
metadata_df.to_csv(metadata_csv_path, index=False)

print(f"\nDone. {len(metadata_df)} total files across {len(subset)} clips x "
      f"({1} clean + {len(NOISE_TYPES)*len(SNR_LEVELS)} noisy conditions).")
print(f"metadata.csv saved to: {metadata_csv_path}")
print(f"Folder ready at: {ROOT}")

# ============================================================
# PART 7 — (OPTIONAL) ZIP + PUSH TO DRIVE FOR THE OTHER 2 ACCOUNTS
# ============================================================
# from google.colab import drive
# drive.mount('/content/drive')
# shutil.make_archive('/content/drive/MyDrive/hinglish_robustness', 'zip', ROOT)
# print("Zipped and saved to Drive — download/re-upload into Colab accounts 2 and 3,")
# print("then unzip to /content/hinglish_robustness so all three accounts use")
# print("IDENTICAL clips, noise mixes, and SNR levels.")

"""
STEP 0 — FULL SETUP FROM SCRATCH
Hindi-English Code-Switched ASR Robustness Benchmark

Run this ONCE (per Colab account, or once and share the resulting folder
via Drive to the other two accounts) before running any model script.

What this does:
1. Installs dependencies
2. Loads MUCS-Hinglish dataset (train/test) and shows you what columns exist
3. Picks a fixed subsample of clips (reproducible via seed)
4. Downloads a small noise set (MUSAN subset via Hugging Face) for
   traffic / babble / indoor noise
5. Builds the exact folder structure from the plan:
     hinglish_robustness/
       clean/
       traffic/{15db,10db,5db}/
       babble/{15db,10db,5db}/
       indoor/{15db,10db,5db}/
       metadata.csv
6. Writes clean + noisy wav files to disk so every model script downstream
   just reads files — no repeated dataset/noise loading, no mismatch risk
   across the 3 Colab accounts.

Run the cells top to bottom. Read the printed dataset inspection output
before continuing to Part 3 — you likely need to adjust the column-name
guesses (AUDIO_COL / TEXT_COL) to match reality.
"""

# ============================================================
# PART 0 — INSTALL
# ============================================================
# !pip install -q datasets soundfile librosa numpy scipy tqdm huggingface_hub pandas

import os
import random
import shutil
import numpy as np
import librosa
import soundfile as sf
import pandas as pd
from tqdm import tqdm
from datasets import load_dataset

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

TARGET_SR = 16000
N_CLIPS = 20          # quick benchmark first; raise to 100-150 once you know timing
SPLIT_TO_USE = "test"  # "test" (3.14k) is a sensible held-out eval pool; use "train" if you prefer
SNR_LEVELS = [15, 10, 5]
NOISE_TYPES = ["traffic", "babble", "indoor"]

ROOT = "/content/hinglish_robustness"
NOISE_SRC_DIR = "/content/noise_src"   # raw downloaded noise, sorted by type

# ============================================================
# PART 1 — LOAD DATASET AND INSPECT IT
# ============================================================
print("Loading MUCS-Hinglish dataset...")
ds = load_dataset("dianavdavidson/MUCS-Hinglish")
print(ds)  # shows splits: train (52.8k), test (3.14k)

example = ds[SPLIT_TO_USE][0]
print("\nExample record keys:", list(example.keys()))
for k, v in example.items():
    preview = str(v)
    if len(preview) > 200:
        preview = preview[:200] + "..."
    print(f"  {k}: {preview}")

# Confirmed from actual dataset inspection:
#   features: audio, segment_id, transcript, speaker_id, segment_part,
#             ratio_english_words, ratio_hindi_words, english_words,
#             count_english_words, count_dev_words, ratio_english_words_range
#   audio is already 16kHz (Audio(sampling_rate=16000)) -> no resampling needed
AUDIO_COL = "audio"
TEXT_COL = "transcript"

assert AUDIO_COL in example, f"'{AUDIO_COL}' not found — check keys above and fix AUDIO_COL"
assert TEXT_COL in example, f"'{TEXT_COL}' not found — check keys above and fix TEXT_COL"

# Code-switching filter: only keep clips that actually contain BOTH Hindi
# and English words, so we're not accidentally benchmarking on monolingual
# segments. ratio_english_words_range looks like a pre-binned category
# (e.g. "0-25", "25-50", ...) — we print unique values once so you can see
# the actual bins and adjust MIN_HINDI_RATIO / MIN_ENGLISH_RATIO below.
print("\nUnique ratio_english_words_range values (sample):")
print(set(ds[SPLIT_TO_USE][:500]["ratio_english_words_range"]))

MIN_HINDI_RATIO = 0.1     # require at least 10% Hindi words
MIN_ENGLISH_RATIO = 0.1   # require at least 10% English words

# ============================================================
# PART 2 — DOWNLOAD NOISE (original MUSAN corpus from OpenSLR)
# ============================================================
# We use the canonical MUSAN corpus directly (not a Hugging Face mirror —
# those vary in schema/quality/availability). This is the same corpus used
# in most ASR robustness papers: https://www.openslr.org/17/
#
# MUSAN structure after extraction:
#   musan/noise/free-sound/*.wav      -> general ambient noise (traffic/indoor proxy)
#   musan/noise/sound-bible/*.wav     -> more ambient noise
#   musan/speech/librivox/*.wav       -> speech -> used as babble (overlapping speech)
#
# Download is ~1.1GB zipped; on Colab's network this typically takes 1-3 min.

import urllib.request
import tarfile

MUSAN_URL = "https://www.openslr.org/resources/17/musan.tar.gz"
MUSAN_TAR_PATH = "/content/musan.tar.gz"
MUSAN_EXTRACT_DIR = "/content/musan_raw"

os.makedirs(NOISE_SRC_DIR, exist_ok=True)
for nt in NOISE_TYPES:
    os.makedirs(os.path.join(NOISE_SRC_DIR, nt), exist_ok=True)

def download_musan():
    if os.path.exists(MUSAN_TAR_PATH):
        print("musan.tar.gz already downloaded, skipping.")
        return
    print(f"Downloading MUSAN from {MUSAN_URL} (about 1.1GB, may take a few minutes)...")
    urllib.request.urlretrieve(MUSAN_URL, MUSAN_TAR_PATH)
    print("Download complete.")

def extract_musan():
    if os.path.exists(MUSAN_EXTRACT_DIR):
        print("MUSAN already extracted, skipping.")
        return
    print("Extracting MUSAN...")
    with tarfile.open(MUSAN_TAR_PATH, "r:gz") as tar:
        tar.extractall(MUSAN_EXTRACT_DIR)
    print("Extraction complete.")

def resample_and_copy(src_path, dst_path):
    arr, sr = librosa.load(src_path, sr=TARGET_SR, mono=True)
    sf.write(dst_path, arr, TARGET_SR)

def populate_noise_folders(n_files_per_type=15):
    musan_root = os.path.join(MUSAN_EXTRACT_DIR, "musan")

    # Sources: noise/free-sound (traffic proxy), noise/sound-bible (indoor proxy),
    # speech/librivox (babble proxy — overlapping speech)
    source_map = {
        "traffic": os.path.join(musan_root, "noise", "free-sound"),
        "indoor": os.path.join(musan_root, "noise", "sound-bible"),
        "babble": os.path.join(musan_root, "speech", "librivox"),
    }

    for noise_type, src_dir in source_map.items():
        if not os.path.isdir(src_dir):
            print(f"[!] Expected folder not found: {src_dir}")
            continue
        wav_files = sorted([f for f in os.listdir(src_dir) if f.endswith(".wav")])
        chosen = wav_files[:n_files_per_type]
        out_dir = os.path.join(NOISE_SRC_DIR, noise_type)
        for f in chosen:
            resample_and_copy(os.path.join(src_dir, f), os.path.join(out_dir, f))
        print(f"  {noise_type}: copied {len(chosen)} files from {src_dir} -> {out_dir}")

try:
    download_musan()
    extract_musan()
    populate_noise_folders(n_files_per_type=15)
except Exception as e:
    print(f"\n[!] MUSAN download/extraction failed: {e}")
    print("    Fallback: manually upload .wav noise files into:")
    for nt in NOISE_TYPES:
        print(f"      {os.path.join(NOISE_SRC_DIR, nt)}/")
    print("    Any real traffic/babble/cafe recordings work — even a few")
    print("    minutes-long clip per category is enough (we crop random")
    print("    segments from it for each mix).")
    print("    You can also manually download musan.tar.gz from")
    print("    https://www.openslr.org/17/ and upload it to /content/,")
    print("    then re-run this cell.")

# ============================================================
# PART 3 — BUILD FOLDER STRUCTURE
# ============================================================
def make_dirs():
    os.makedirs(os.path.join(ROOT, "clean"), exist_ok=True)
    for nt in NOISE_TYPES:
        for snr in SNR_LEVELS:
            os.makedirs(os.path.join(ROOT, nt, f"{snr}db"), exist_ok=True)

make_dirs()
print(f"\nFolder structure created under {ROOT}")

# ============================================================
# PART 4 — SUBSAMPLE CLIPS (filtered for genuine code-switching)
# ============================================================
data = ds[SPLIT_TO_USE]

print("\nFiltering for genuinely code-switched clips "
      f"(Hindi ratio >= {MIN_HINDI_RATIO}, English ratio >= {MIN_ENGLISH_RATIO})...")
cs_data = data.filter(
    lambda ex: ex["ratio_hindi_words"] >= MIN_HINDI_RATIO
    and ex["ratio_english_words"] >= MIN_ENGLISH_RATIO
)
print(f"Code-switched clips available: {len(cs_data)} / {len(data)}")

if len(cs_data) < N_CLIPS:
    print(f"[!] Only {len(cs_data)} clips pass the filter, fewer than N_CLIPS={N_CLIPS}. "
          "Lower MIN_HINDI_RATIO / MIN_ENGLISH_RATIO or increase N_CLIPS accordingly.")

indices = list(range(len(cs_data)))
random.shuffle(indices)
indices = indices[:N_CLIPS]
subset = cs_data.select(indices)
print(f"\nUsing {len(subset)} clips from split '{SPLIT_TO_USE}' (seed={SEED})")

# ============================================================
# PART 5 — NOISE MIXING UTILITIES
# ============================================================
def load_noise_files(noise_type):
    folder = os.path.join(NOISE_SRC_DIR, noise_type)
    files = [os.path.join(folder, f) for f in os.listdir(folder) if f.endswith(".wav")]
    if not files:
        raise FileNotFoundError(
            f"No noise wavs found in {folder}. See Part 2 fallback instructions above."
        )
    return files

noise_file_cache = {nt: load_noise_files(nt) for nt in NOISE_TYPES}

def get_random_noise_clip(noise_type, target_len):
    files = noise_file_cache[noise_type]
    path = random.choice(files)
    noise, sr = librosa.load(path, sr=TARGET_SR, mono=True)
    if len(noise) < target_len:
        reps = int(np.ceil(target_len / len(noise)))
        noise = np.tile(noise, reps)
    start = random.randint(0, len(noise) - target_len) if len(noise) > target_len else 0
    return noise[start:start + target_len]

def mix_at_snr(clean, noise, snr_db):
    clean_power = np.mean(clean ** 2) + 1e-10
    noise_power = np.mean(noise ** 2) + 1e-10
    target_noise_power = clean_power / (10 ** (snr_db / 10))
    scale = np.sqrt(target_noise_power / noise_power)
    noisy = clean + noise * scale
    peak = np.max(np.abs(noisy))
    if peak > 1.0:
        noisy = noisy / peak
    return noisy.astype(np.float32)

def get_audio_array(sample):
    audio = sample[AUDIO_COL]
    arr = np.array(audio["array"], dtype=np.float32)
    sr = audio["sampling_rate"]
    if sr != TARGET_SR:
        arr = librosa.resample(arr, orig_sr=sr, target_sr=TARGET_SR)
    return arr

# ============================================================
# PART 6 — GENERATE CLEAN + NOISY FILES, BUILD metadata.csv
# ============================================================
metadata_rows = []

print("\nWriting clean files...")
for i, sample in enumerate(tqdm(subset)):
    clean_audio = get_audio_array(sample)
    reference = sample[TEXT_COL]
    clip_id = f"clip_{i:04d}"

    clean_path = os.path.join(ROOT, "clean", f"{clip_id}.wav")
    sf.write(clean_path, clean_audio, TARGET_SR)

    base_meta = {
        "clip_id": clip_id,
        "segment_id": sample.get("segment_id"),
        "speaker_id": sample.get("speaker_id"),
        "ratio_english_words": sample.get("ratio_english_words"),
        "ratio_hindi_words": sample.get("ratio_hindi_words"),
    }

    metadata_rows.append({
        **base_meta,
        "condition": "clean",
        "noise_type": "none",
        "snr_db": "clean",
        "filepath": clean_path,
        "reference_text": reference,
        "duration_sec": len(clean_audio) / TARGET_SR,
    })

    for noise_type in NOISE_TYPES:
        for snr in SNR_LEVELS:
            noise_clip = get_random_noise_clip(noise_type, len(clean_audio))
            noisy_audio = mix_at_snr(clean_audio, noise_clip, snr)
            noisy_path = os.path.join(ROOT, noise_type, f"{snr}db", f"{clip_id}.wav")
            sf.write(noisy_path, noisy_audio, TARGET_SR)

            metadata_rows.append({
                **base_meta,
                "condition": noise_type,
                "noise_type": noise_type,
                "snr_db": snr,
                "filepath": noisy_path,
                "reference_text": reference,
                "duration_sec": len(clean_audio) / TARGET_SR,
            })

metadata_df = pd.DataFrame(metadata_rows)
metadata_csv_path = os.path.join(ROOT, "metadata.csv")
metadata_df.to_csv(metadata_csv_path, index=False)

print(f"\nDone. {len(metadata_df)} total files across {len(subset)} clips x "
      f"({1} clean + {len(NOISE_TYPES)*len(SNR_LEVELS)} noisy conditions).")
print(f"metadata.csv saved to: {metadata_csv_path}")
print(f"Folder ready at: {ROOT}")

# ============================================================
# PART 7 — (OPTIONAL) ZIP + PUSH TO DRIVE FOR THE OTHER 2 ACCOUNTS
# ============================================================
# from google.colab import drive
# drive.mount('/content/drive')
# shutil.make_archive('/content/drive/MyDrive/hinglish_robustness', 'zip', ROOT)
# print("Zipped and saved to Drive — download/re-upload into Colab accounts 2 and 3,")
# print("then unzip to /content/hinglish_robustness so all three accounts use")
# print("IDENTICAL clips, noise mixes, and SNR levels.")

!pip install -q transformers jiwer soundfile librosa pandas tqdm

"""
Account 1 — Whisper (Small) Inference + Scoring
Reads the files/metadata.csv already produced by step0_setup_from_scratch.py
Does NOT re-load the dataset or re-mix noise — that's step0's job.

To swap models later (Account 2 / 3), you only need to change the
CONFIG block and the two functions marked "MODEL-SPECIFIC" below.
Everything else (data loading, scoring, CSV output) stays identical
across all model scripts so results merge cleanly.
"""

# ============================================================
# CONFIG  <-- this is basically the only section that changes per model
# ============================================================
MODEL_ID = "openai/whisper-small"     # e.g. swap to "openai/whisper-medium"
MODEL_TAG = "whisper_small"           # used in output filenames

ROOT = "/content/hinglish_robustness"          # must match step0's ROOT
METADATA_CSV = f"{ROOT}/metadata.csv"
OUTPUT_DIR = "/content/results"
RESULTS_CSV = f"{OUTPUT_DIR}/results_{MODEL_TAG}.csv"
SUMMARY_CSV = f"{OUTPUT_DIR}/summary_{MODEL_TAG}.csv"

# ============================================================
# SETUP
# ============================================================
# !pip install -q transformers jiwer soundfile librosa pandas tqdm

import os
import time
import torch
import librosa
import pandas as pd
from tqdm import tqdm
from jiwer import wer, cer

os.makedirs(OUTPUT_DIR, exist_ok=True)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

TARGET_SR = 16000

# ============================================================
# LOAD MODEL — MODEL-SPECIFIC
# ============================================================
from transformers import WhisperProcessor, WhisperForConditionalGeneration

processor = WhisperProcessor.from_pretrained(MODEL_ID)
model = WhisperForConditionalGeneration.from_pretrained(MODEL_ID).to(device)
model.eval()

forced_decoder_ids = processor.get_decoder_prompt_ids(language="hi", task="transcribe")

@torch.no_grad()
def transcribe(audio_array, sr=TARGET_SR):
    """MODEL-SPECIFIC: swap this function's internals for other models."""
    inputs = processor(audio_array, sampling_rate=sr, return_tensors="pt")
    input_features = inputs.input_features.to(device)
    predicted_ids = model.generate(
        input_features,
        forced_decoder_ids=forced_decoder_ids,
        max_new_tokens=225,
    )
    text = processor.batch_decode(predicted_ids, skip_special_tokens=True)[0]
    return text.strip()

# ============================================================
# LOAD METADATA (produced by step0 — identical across all 3 accounts)
# ============================================================
assert os.path.exists(METADATA_CSV), (
    f"metadata.csv not found at {METADATA_CSV}. "
    "Run step0_setup_from_scratch.py first (or copy the hinglish_robustness "
    "folder from Drive into this Colab account)."
)

meta = pd.read_csv(METADATA_CSV)
print(f"Loaded metadata: {len(meta)} rows "
      f"({meta['clip_id'].nunique()} clips x {meta['condition'].nunique()} conditions)")

# ============================================================
# RUN INFERENCE OVER EVERY FILE IN metadata.csv
# ============================================================
results = []
start_time = time.time()

for _, row in tqdm(meta.iterrows(), total=len(meta)):
    filepath = row["filepath"]
    reference = str(row["reference_text"])

    audio_array, sr = librosa.load(filepath, sr=TARGET_SR, mono=True)

    t0 = time.time()
    hypothesis = transcribe(audio_array, sr=TARGET_SR)
    latency = time.time() - t0

    sample_wer = wer(reference, hypothesis) if reference.strip() else None
    sample_cer = cer(reference, hypothesis) if reference.strip() else None

    results.append({
        "model": MODEL_TAG,
        "clip_id": row["clip_id"],
        "segment_id": row.get("segment_id"),
        "speaker_id": row.get("speaker_id"),
        "condition": row["condition"],
        "noise_type": row["noise_type"],
        "snr_db": row["snr_db"],
        "ratio_english_words": row.get("ratio_english_words"),
        "ratio_hindi_words": row.get("ratio_hindi_words"),
        "reference": reference,
        "hypothesis": hypothesis,
        "wer": sample_wer,
        "cer": sample_cer,
        "latency_sec": latency,
    })

elapsed = time.time() - start_time
n_clips = meta["clip_id"].nunique()
print(f"\nTotal runtime: {elapsed/60:.1f} min for {len(meta)} inferences "
      f"({n_clips} clips x {meta['condition'].nunique()} conditions)")
print(f"Avg latency per inference: {elapsed/len(meta):.2f} sec")

# ============================================================
# SAVE RESULTS
# ============================================================
df = pd.DataFrame(results)
df.to_csv(RESULTS_CSV, index=False)
print(f"Saved: {RESULTS_CSV}")

# ============================================================
# SUMMARY: mean WER per condition + relative degradation
# ============================================================
summary = df.groupby(["condition", "snr_db"])["wer"].mean().reset_index()
clean_wer = df[df["condition"] == "clean"]["wer"].mean()
summary["relative_degradation_pct"] = ((summary["wer"] - clean_wer) / clean_wer) * 100
summary.to_csv(SUMMARY_CSV, index=False)

print("\nSummary (mean WER by condition):")
print(summary)
print(f"Saved: {SUMMARY_CSV}")

from google.colab import drive
drive.mount('/content/drive')

import os

BACKUP_ROOT = "/content/drive/MyDrive/Hinglish_ASR_Research_2026"
os.makedirs(BACKUP_ROOT, exist_ok=True)

print("Backup folder:", BACKUP_ROOT)

import shutil
import os

items = [
    "/content/hinglish_robustness",
    "/content/musan_raw",
    "/content/noise_src",
    "/content/results",
    "/content/musan.tar.gz"
]

for src in items:
    if os.path.exists(src):
        dst = os.path.join(BACKUP_ROOT, os.path.basename(src))

        if os.path.isdir(src):
            shutil.copytree(src, dst, dirs_exist_ok=True)
        else:
            shutil.copy2(src, dst)

        print("Backed up:", src)
    else:
        print("NOT FOUND:", src)

print("\nBackup completed.")

"""When Step 0 ran, it downloaded the entire MUSAN noise dataset (a ~1.1 GB zip file) and unzipped it (~1.1 GB more) — but you only actually needed about 45 small audio clips out of it. The rest is just sitting there unused, taking up space."""

import shutil, os

if os.path.exists("/content/musan.tar.gz"):
    os.remove("/content/musan.tar.gz")
if os.path.exists("/content/musan_raw"):
    shutil.rmtree("/content/musan_raw")

print("Cleaned up. Checking disk space now:")
!df -h /content

"""
Account 2 — XLS-R / Wav2Vec2 (multilingual) Inference + Scoring
Reads the files/metadata.csv already produced by step0_setup_from_scratch.py
Does NOT re-load the dataset or re-mix noise — that's step0's job.

Same structure as model_whisper_inference.py — only the CONFIG block and
the "MODEL-SPECIFIC" section differ, so results merge cleanly.
"""

# ============================================================
# CONFIG
# ============================================================
# A genuinely multilingual XLS-R checkpoint fine-tuned for Hindi ASR.
# This one is CTC-based (not seq2seq like Whisper), so decoding differs.
# If this exact checkpoint isn't available/suitable, swap to any
# Wav2Vec2ForCTC / XLS-R Hindi or multilingual model on the Hub.
MODEL_ID = "theainerd/Wav2Vec2-large-xlsr-hindi"   # verify this still exists / try alternatives below
MODEL_TAG = "xlsr_wav2vec2"

ROOT = "/content/hinglish_robustness"          # must match step0's ROOT
METADATA_CSV = f"{ROOT}/metadata.csv"
OUTPUT_DIR = "/content/results"
RESULTS_CSV = f"{OUTPUT_DIR}/results_{MODEL_TAG}.csv"
SUMMARY_CSV = f"{OUTPUT_DIR}/summary_{MODEL_TAG}.csv"

# Alternative checkpoints to try if the above 404s or underperforms badly:
#   "facebook/wav2vec2-large-xlsr-53"                 (needs a Hindi-tuned head; raw model has no LM head for hi)
#   "Harveenchadha/vakyansh-wav2vec2-hindi-him-4200"   (Hindi-specific, well-used)
#   "ai4bharat/indicwav2vec-hindi"                     (if available on the Hub)

# ============================================================
# SETUP
# ============================================================
# !pip install -q transformers jiwer soundfile librosa pandas tqdm

import os
import time
import torch
import librosa
import pandas as pd
from tqdm import tqdm
from jiwer import wer, cer

os.makedirs(OUTPUT_DIR, exist_ok=True)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

TARGET_SR = 16000

# ============================================================
# LOAD MODEL — MODEL-SPECIFIC
# ============================================================
from transformers import Wav2Vec2ForCTC, Wav2Vec2Processor

processor = Wav2Vec2Processor.from_pretrained(MODEL_ID)
model = Wav2Vec2ForCTC.from_pretrained(MODEL_ID).to(device)
model.eval()

@torch.no_grad()
def transcribe(audio_array, sr=TARGET_SR):
    """MODEL-SPECIFIC: CTC greedy decoding (no forced language prompt needed,
    since the checkpoint is already Hindi/multilingual-specific)."""
    inputs = processor(audio_array, sampling_rate=sr, return_tensors="pt", padding=True)
    input_values = inputs.input_values.to(device)
    logits = model(input_values).logits
    predicted_ids = torch.argmax(logits, dim=-1)
    text = processor.batch_decode(predicted_ids)[0]
    return text.strip()

# ============================================================
# LOAD METADATA (produced by step0 — identical across all 3 accounts)
# ============================================================
assert os.path.exists(METADATA_CSV), (
    f"metadata.csv not found at {METADATA_CSV}. "
    "Run step0_setup_from_scratch.py first (or copy the hinglish_robustness "
    "folder from Drive into this Colab account)."
)

meta = pd.read_csv(METADATA_CSV)
print(f"Loaded metadata: {len(meta)} rows "
      f"({meta['clip_id'].nunique()} clips x {meta['condition'].nunique()} conditions)")

# ============================================================
# RUN INFERENCE OVER EVERY FILE IN metadata.csv
# ============================================================
results = []
start_time = time.time()

for _, row in tqdm(meta.iterrows(), total=len(meta)):
    filepath = row["filepath"]
    reference = str(row["reference_text"])

    audio_array, sr = librosa.load(filepath, sr=TARGET_SR, mono=True)

    t0 = time.time()
    hypothesis = transcribe(audio_array, sr=TARGET_SR)
    latency = time.time() - t0

    sample_wer = wer(reference, hypothesis) if reference.strip() else None
    sample_cer = cer(reference, hypothesis) if reference.strip() else None

    results.append({
        "model": MODEL_TAG,
        "clip_id": row["clip_id"],
        "segment_id": row.get("segment_id"),
        "speaker_id": row.get("speaker_id"),
        "condition": row["condition"],
        "noise_type": row["noise_type"],
        "snr_db": row["snr_db"],
        "ratio_english_words": row.get("ratio_english_words"),
        "ratio_hindi_words": row.get("ratio_hindi_words"),
        "reference": reference,
        "hypothesis": hypothesis,
        "wer": sample_wer,
        "cer": sample_cer,
        "latency_sec": latency,
    })

elapsed = time.time() - start_time
n_clips = meta["clip_id"].nunique()
print(f"\nTotal runtime: {elapsed/60:.1f} min for {len(meta)} inferences "
      f"({n_clips} clips x {meta['condition'].nunique()} conditions)")
print(f"Avg latency per inference: {elapsed/len(meta):.2f} sec")

# ============================================================
# SAVE RESULTS
# ============================================================
df = pd.DataFrame(results)
df.to_csv(RESULTS_CSV, index=False)
print(f"Saved: {RESULTS_CSV}")

# ============================================================
# SUMMARY: mean WER per condition + relative degradation
# ============================================================
summary = df.groupby(["condition", "snr_db"])["wer"].mean().reset_index()
clean_wer = df[df["condition"] == "clean"]["wer"].mean()
summary["relative_degradation_pct"] = ((summary["wer"] - clean_wer) / clean_wer) * 100
summary.to_csv(SUMMARY_CSV, index=False)

print("\nSummary (mean WER by condition):")
print(summary)
print(f"Saved: {SUMMARY_CSV}")

import os

BACKUP_ROOT = "/content/drive/MyDrive/Hinglish_ASR_Research_Backup"
os.makedirs(BACKUP_ROOT, exist_ok=True)

print(BACKUP_ROOT)

!df -h /content/drive

from google.colab import drive
drive.mount('/content/drive')

import os
import shutil

BACKUP = "/content/drive/MyDrive/Hinglish_ASR_Backup"
os.makedirs(BACKUP, exist_ok=True)

for filename in [
    "/content/results/results_xlsr_wav2vec2.csv",
    "/content/results/summary_xlsr_wav2vec2.csv",
]:
    shutil.copy2(filename, BACKUP)

print("Account 2 results backed up!")

shutil.copytree(
    "/content/hinglish_robustness",
    os.path.join(BACKUP_ROOT, "hinglish_robustness"),
    dirs_exist_ok=True
)

print("Benchmark dataset backed up.")

from google.colab import drive
drive.mount('/content/drive')

import shutil, os
DRIVE_FOLDER = "/content/drive/MyDrive/Hinglish_ASR_Research_2026"  # adjust if your path differs
LOCAL_FOLDER = "/content/Hinglish_ASR_Research_2026"

if not os.path.exists(LOCAL_FOLDER):
    shutil.copytree(DRIVE_FOLDER, LOCAL_FOLDER)
    print("Copied from Drive to local disk.")
else:
    print("Already exists locally.")

import os
import time
import torch
import librosa
import pandas as pd
from tqdm import tqdm
from jiwer import wer, cer

from huggingface_hub import login
login()

from google.colab import drive
drive.mount('/content/drive')

import os
BASE = "/content/drive/MyDrive/Hinglish_ASR_Research_2026"
for root, dirs, files in os.walk(BASE):
    print(root, "->", dirs, files[:5])

print("ROOT =", ROOT)
import os
print("ROOT exists:", os.path.exists(ROOT))
print("Contents of ROOT:", os.listdir(ROOT) if os.path.exists(ROOT) else "N/A")

meta = pd.read_csv(METADATA_CSV)
print(f"Loaded metadata: {len(meta)} rows")

def rebuild_filepath(row):
    if row["condition"] == "clean":
        return os.path.join(ROOT, "clean", f"{row['clip_id']}.wav")
    else:
        return os.path.join(ROOT, row["condition"], f"{row['snr_db']}db", f"{row['clip_id']}.wav")

meta["filepath"] = meta.apply(rebuild_filepath, axis=1)

missing = meta[~meta["filepath"].apply(os.path.exists)]
print(f"Missing files: {len(missing)}")
print("Sample filepath:", meta["filepath"].iloc[0])
print("That file exists:", os.path.exists(meta["filepath"].iloc[0]))

"""
Account 3 — Indic Model (AI4Bharat IndicWav2Vec — Hindi) Inference + Scoring
Reads the files/metadata.csv already produced by step0_setup_from_scratch.py
Does NOT re-load the dataset or re-mix noise — that's step0's job.

Same structure as model_whisper_inference.py / model_xlsr_inference.py —
only the CONFIG block and the "MODEL-SPECIFIC" section differ.
"""

# ============================================================
# CONFIG
# ============================================================
# AI4Bharat's IndicWav2Vec is trained specifically on Indian languages
# (including Hindi), making it the "Indic-focused" model in the comparison.
# It is CTC-based, same family as Model B, but trained on very different
# (India-specific, more code-switch-adjacent) data.
MODEL_ID = "ai4bharat/indicwav2vec-hindi"     # verify availability; fallback below
MODEL_TAG = "indicwav2vec_hindi"

ROOT = "/content/drive/MyDrive/Hinglish_ASR_Research_2026/hinglish_robustness"         # must match step0's ROOT
METADATA_CSV = f"{ROOT}/metadata.csv"
OUTPUT_DIR = "/content/results"
RESULTS_CSV = f"{OUTPUT_DIR}/results_{MODEL_TAG}.csv"
SUMMARY_CSV = f"{OUTPUT_DIR}/summary_{MODEL_TAG}.csv"

# Alternative checkpoints to try if the above 404s or underperforms badly:
#   "ai4bharat/indicwav2vec_v1_hindi"
#   "Harveenchadha/vakyansh-wav2vec2-hindi-him-4200"   (same as Model B fallback —
#        if you use this, pick a DIFFERENT one for Model B/C to keep them distinct)
#   "ai4bharat/indic-conformer-600m-multilingual"      (Conformer-based; if you use
#        this instead, decoding differs — check its model card for usage, since
#        it may use a different processor/decoder API than plain Wav2Vec2ForCTC)

# ============================================================
# SETUP
# ============================================================
# !pip install -q transformers jiwer soundfile librosa pandas tqdm

import os
import time
import torch
import librosa
import pandas as pd
from tqdm import tqdm
from jiwer import wer, cer

os.makedirs(OUTPUT_DIR, exist_ok=True)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

TARGET_SR = 16000

# ============================================================
# LOAD MODEL — MODEL-SPECIFIC
# ============================================================
from transformers import Wav2Vec2ForCTC, Wav2Vec2Processor

processor = Wav2Vec2Processor.from_pretrained(MODEL_ID)
model = Wav2Vec2ForCTC.from_pretrained(MODEL_ID).to(device)
model.eval()

@torch.no_grad()
def transcribe(audio_array, sr=TARGET_SR):
    """MODEL-SPECIFIC: CTC greedy decoding, same pattern as Model B.
    If you swap to a Conformer-based Indic model instead, this function
    (and possibly the processor/model classes above) will need to change
    to match that model's actual inference API — check its model card."""
    inputs = processor(audio_array, sampling_rate=sr, return_tensors="pt", padding=True)
    input_values = inputs.input_values.to(device)
    logits = model(input_values).logits
    predicted_ids = torch.argmax(logits, dim=-1)
    text = processor.batch_decode(predicted_ids)[0]
    return text.strip()

# ============================================================
# LOAD METADATA (produced by step0 — identical across all 3 accounts)
# ============================================================
assert os.path.exists(METADATA_CSV), (
    f"metadata.csv not found at {METADATA_CSV}. "
    "Run step0_setup_from_scratch.py first (or copy the hinglish_robustness "
    "folder from Drive into this Colab account)."
)

meta = pd.read_csv(METADATA_CSV)
print(f"Loaded metadata: {len(meta)} rows "
      f"({meta['clip_id'].nunique()} clips x {meta['condition'].nunique()} conditions)")

# Rebuild filepath so it matches wherever the data actually lives right now
# (metadata.csv has stale paths from the original session)
def rebuild_filepath(row):
    if row["condition"] == "clean":
        return os.path.join(ROOT, "clean", f"{row['clip_id']}.wav")
    else:
        return os.path.join(ROOT, row["condition"], f"{row['snr_db']}db", f"{row['clip_id']}.wav")

meta["filepath"] = meta.apply(rebuild_filepath, axis=1)

missing = meta[~meta["filepath"].apply(os.path.exists)]
if len(missing) > 0:
    print(f"[!] WARNING: {len(missing)} files not found. First few:")
    print(missing[["clip_id", "condition", "snr_db", "filepath"]].head())
else:
    print("All filepaths verified to exist.")
# ============================================================
# RUN INFERENCE OVER EVERY FILE IN metadata.csv
# ============================================================
results = []
start_time = time.time()

for _, row in tqdm(meta.iterrows(), total=len(meta)):
    filepath = row["filepath"]
    reference = str(row["reference_text"])

    audio_array, sr = librosa.load(filepath, sr=TARGET_SR, mono=True)

    t0 = time.time()
    hypothesis = transcribe(audio_array, sr=TARGET_SR)
    latency = time.time() - t0

    sample_wer = wer(reference, hypothesis) if reference.strip() else None
    sample_cer = cer(reference, hypothesis) if reference.strip() else None

    results.append({
        "model": MODEL_TAG,
        "clip_id": row["clip_id"],
        "segment_id": row.get("segment_id"),
        "speaker_id": row.get("speaker_id"),
        "condition": row["condition"],
        "noise_type": row["noise_type"],
        "snr_db": row["snr_db"],
        "ratio_english_words": row.get("ratio_english_words"),
        "ratio_hindi_words": row.get("ratio_hindi_words"),
        "reference": reference,
        "hypothesis": hypothesis,
        "wer": sample_wer,
        "cer": sample_cer,
        "latency_sec": latency,
    })

elapsed = time.time() - start_time
n_clips = meta["clip_id"].nunique()
print(f"\nTotal runtime: {elapsed/60:.1f} min for {len(meta)} inferences "
      f"({n_clips} clips x {meta['condition'].nunique()} conditions)")
print(f"Avg latency per inference: {elapsed/len(meta):.2f} sec")

# ============================================================
# SAVE RESULTS
# ============================================================
df = pd.DataFrame(results)
df.to_csv(RESULTS_CSV, index=False)
print(f"Saved: {RESULTS_CSV}")

# ============================================================
# SUMMARY: mean WER per condition + relative degradation
# ============================================================
summary = df.groupby(["condition", "snr_db"])["wer"].mean().reset_index()
clean_wer = df[df["condition"] == "clean"]["wer"].mean()
summary["relative_degradation_pct"] = ((summary["wer"] - clean_wer) / clean_wer) * 100
summary.to_csv(SUMMARY_CSV, index=False)

print("\nSummary (mean WER by condition):")
print(summary)
print(f"Saved: {SUMMARY_CSV}")
